from dataclasses import dataclass

@dataclass
class config_model:
    num_classes :int = ...
    conv1:int = ...
    ...

    # Define the configurations required in model architecture

@dataclass
class config_train:
    #dataloaders parameters
  
    batch_size:int = ...
    ...
    # training paramerters 
    learning_rate: float = ...
    weight_decay: float = ...
    ...
